//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 3.3.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.Wikipedia;

namespace Wikipedia_Model.Screens
{
	public partial class  MainScreen : BaseScreen
	{
		public  MainScreen(IAppBasics appBasics) : base(appBasics, "Main Screen", Images.MainScreen.Screen_Loaded)
		{
			
			ConfigureElementProperties();
        }

		
		partial void ConfigureElementProperties();
	}
}