//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 3.3.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.Wikipedia;

namespace Wikipedia_Model.Screens
{
	public partial class  TopMenu : BaseScreen
	{
		public  TopMenu(IAppBasics appBasics) : base(appBasics, "Top Menu", Images.TopMenu.Screen_Loaded)
		{
			CreateAccount = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Create account", activeImageReference: Images.TopMenu.CreateAccount.active, filters: ScreenSelect) { ParentScreen = this }; 
			LogIn = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Log in", activeImageReference: Images.TopMenu.LogIn.active, filters: ScreenSelect) { ParentScreen = this }; 
			LogOut = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Log out", activeImageReference: Images.TopMenu.LogOut.active, filters: ScreenSelect) { ParentScreen = this }; 
			LoggedInUser = new Progile.TRIO.BaseModel.LabelWithValue(tester: t, displayName: "Logged in user", valuePosition: RelativePosition.Right, imageReferenceForLabel: Images.TopMenu.LoggedInUser, gridWidth: 800, filters: ScreenSelect) { ParentScreen = this }; 
			
			ConfigureElementProperties();
        }

		  
		public Progile.TRIO.BaseModel.Button CreateAccount { get; private set; }
		  
		public Progile.TRIO.BaseModel.Button LogIn { get; private set; }
		  
		public Progile.TRIO.BaseModel.Button LogOut { get; private set; }
		  
		public Progile.TRIO.BaseModel.LabelWithValue LoggedInUser { get; private set; }
		
		partial void ConfigureElementProperties();
	}
}