//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 3.3.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.Wikipedia;

namespace Wikipedia_Model.Screens
{
	public partial class  WelcomeScreen : BaseScreen
	{
		public  WelcomeScreen(IAppBasics appBasics) : base(appBasics, "Welcome Screen", Images.WelcomeScreen.Screen_Loaded)
		{
			English = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "English", activeImageReference: Images.WelcomeScreen.English.active, filters: ScreenSelect) { ParentScreen = this }; 
			German = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "German", activeImageReference: Images.WelcomeScreen.German.active, filters: ScreenSelect) { ParentScreen = this }; 
			
			ConfigureElementProperties();
        }

		  
		public Progile.TRIO.BaseModel.Button English { get; private set; }
		  
		public Progile.TRIO.BaseModel.Button German { get; private set; }
		
		partial void ConfigureElementProperties();
	}
}