//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 3.3.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using Wikipedia_Model.Screens;
 
namespace Wikipedia_Model
{
	public partial class WikipediaApp : IAppBasics
    {
        partial void InitScreens()
        {
			WelcomeScreen = new WelcomeScreen(this);
			MainScreen = new MainScreen(this);
			LoginScreen = new LoginScreen(this);
			TopMenu = new TopMenu(this);
        }

		  
		public WelcomeScreen WelcomeScreen { get; set; }
		  
		public MainScreen MainScreen { get; set; }
		  
		public LoginScreen LoginScreen { get; set; }
		  
		public TopMenu TopMenu { get; set; }
		
    }
}